/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package marketingsoftware;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author DC
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        jLoginTab = jMainTabbedPane.getComponentAt(0);
        jRegisterTabInMemory = jMainTabbedPane.getComponentAt(1);
        jMainTabbedPane.remove(1);
        addproduct  = jMainTabbedPane.getComponentAt(1);
        jMainTabbedPane.remove(1);
        displayproduct = jMainTabbedPane.getComponentAt(1);
        jMainTabbedPane.remove(1);
        basketTab = jMainTabbedPane.getComponentAt(1);
        jMainTabbedPane.remove(1);
        reorder = jMainTabbedPane.getComponentAt(1);
        jMainTabbedPane.remove(1);
        addsupplier = jMainTabbedPane.getComponentAt(1);
        jMainTabbedPane.remove(1);
        showorders = jMainTabbedPane.getComponentAt(1);
        jMainTabbedPane.remove(1);
        jMainTabbedPane.setSelectedIndex(0); 
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jStatusPanel = new javax.swing.JPanel();
        jMainPanel = new javax.swing.JPanel();
        jMainTabbedPane = new javax.swing.JTabbedPane();
        jLoginPanel = new javax.swing.JPanel();
        jLoginComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLoginEmailTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLoginButton = new javax.swing.JButton();
        jLoginRegisterButton = new javax.swing.JButton();
        jLoginPasswordField = new javax.swing.JPasswordField();
        jLabel32 = new javax.swing.JLabel();
        jRegisterPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jRegisterPW2TextField = new javax.swing.JTextField();
        jRegisterPWTextField = new javax.swing.JTextField();
        jRegisterEmailTextField = new javax.swing.JTextField();
        jRegisterSurnameTextField = new javax.swing.JTextField();
        jRegisterNameTextField = new javax.swing.JTextField();
        jRegisterComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jRegisterButton = new javax.swing.JButton();
        jProductPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPIDTextField = new javax.swing.JTextField();
        jPNameTextField = new javax.swing.JTextField();
        jPWeightTextField = new javax.swing.JTextField();
        jPPriceTextField = new javax.swing.JTextField();
        jPExpiryTextField = new javax.swing.JTextField();
        jPOrderTextField = new javax.swing.JTextField();
        jSaveProductButton = new javax.swing.JButton();
        jUploadImageButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jUploadImageLabel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPNumberTextField = new javax.swing.JTextField();
        jDisplayProductPanel = new javax.swing.JPanel();
        jDisplayProductLabel = new javax.swing.JLabel();
        jDisplayProductComboBox = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDiaplayProductTextArea = new javax.swing.JTextArea();
        jDisplayProductButton = new javax.swing.JButton();
        AddtoBasket = new javax.swing.JButton();
        jDisplayProduct_WishListButton = new javax.swing.JButton();
        jBasketPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jBasketTextArea = new javax.swing.JTextArea();
        jremovefrombasketButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jshowPriceButton = new javax.swing.JButton();
        jDisplayBAsketButton = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPlaceOrderBasketButton = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jaddWishListButton = new javax.swing.JButton();
        jReorderPanel = new javax.swing.JPanel();
        jSelectProductComboBox = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jExpectedDeliveryDateTextField = new javax.swing.JTextField();
        jAmountPaidLabel = new javax.swing.JLabel();
        jNumberOfProductSpinner = new javax.swing.JSpinner();
        jSelectSupplierComboBox = new javax.swing.JComboBox<>();
        jPlaceOrderButton = new javax.swing.JButton();
        jShowSupplierButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jSupplierDetailTextArea = new javax.swing.JTextArea();
        jAmountButton = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jAddSupplierPanel = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jSaveSupplierButton = new javax.swing.JButton();
        jNameTextField = new javax.swing.JTextField();
        jBuildingNoTextField = new javax.swing.JTextField();
        jStreetTextField = new javax.swing.JTextField();
        jAreaTextField = new javax.swing.JTextField();
        jPostCodeTextField = new javax.swing.JTextField();
        jTownTextField = new javax.swing.JTextField();
        jCountryTextField = new javax.swing.JTextField();
        jShowOrdersPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jDisplayOrdersTextArea = new javax.swing.JTextArea();
        jDisplayPendingOrdersButton = new javax.swing.JButton();
        jSupplyProductButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jStatusPanelLayout = new javax.swing.GroupLayout(jStatusPanel);
        jStatusPanel.setLayout(jStatusPanelLayout);
        jStatusPanelLayout.setHorizontalGroup(
            jStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jStatusPanelLayout.setVerticalGroup(
            jStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jLoginComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Owner", "Customer", "Supplier" }));

        jLabel1.setText("User Email :");

        jLabel2.setText("Password :");

        jLabel3.setText("Select Role :");

        jLoginButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLoginButton.setText("Login");
        jLoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButtonActionPerformed(evt);
            }
        });

        jLoginRegisterButton.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLoginRegisterButton.setText("New Here!!! Create an account first.");
        jLoginRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginRegisterButtonActionPerformed(evt);
            }
        });

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marketingsoftware/istockphoto-1127711786-612x612.jpg"))); // NOI18N
        jLabel32.setMaximumSize(new java.awt.Dimension(2000, 2000));
        jLabel32.setName(""); // NOI18N
        jLabel32.setPreferredSize(new java.awt.Dimension(2000, 2000));

        javax.swing.GroupLayout jLoginPanelLayout = new javax.swing.GroupLayout(jLoginPanel);
        jLoginPanel.setLayout(jLoginPanelLayout);
        jLoginPanelLayout.setHorizontalGroup(
            jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoginPanelLayout.createSequentialGroup()
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLoginPanelLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jLoginPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLoginEmailTextField))
                            .addGroup(jLoginPanelLayout.createSequentialGroup()
                                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(16, 16, 16)
                                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLoginButton)
                                    .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLoginComboBox, 0, 181, Short.MAX_VALUE)
                                        .addComponent(jLoginPasswordField))))))
                    .addGroup(jLoginPanelLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLoginRegisterButton)))
                .addGap(18, 18, 18)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jLoginPanelLayout.setVerticalGroup(
            jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoginPanelLayout.createSequentialGroup()
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLoginPanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLoginEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLoginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLoginComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jLoginButton)
                        .addGap(63, 63, 63)
                        .addComponent(jLoginRegisterButton))
                    .addGroup(jLoginPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jMainTabbedPane.addTab("Login", jLoginPanel);

        jLabel4.setText("Name :");

        jLabel5.setText("Surname :");

        jLabel6.setText("E-mail :");

        jLabel7.setText("Password :");

        jLabel8.setText("Confirm Password :");

        jRegisterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Owner", "Customer", "Supplier" }));
        jRegisterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegisterComboBoxActionPerformed(evt);
            }
        });

        jLabel9.setText("Select Role :");

        jRegisterButton.setText("Register");
        jRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegisterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jRegisterPanelLayout = new javax.swing.GroupLayout(jRegisterPanel);
        jRegisterPanel.setLayout(jRegisterPanelLayout);
        jRegisterPanelLayout.setHorizontalGroup(
            jRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRegisterPanelLayout.createSequentialGroup()
                .addGroup(jRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jRegisterPanelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRegisterComboBox, 0, 125, Short.MAX_VALUE)
                            .addComponent(jRegisterPW2TextField)
                            .addComponent(jRegisterPWTextField)
                            .addComponent(jRegisterEmailTextField)
                            .addComponent(jRegisterSurnameTextField)
                            .addComponent(jRegisterNameTextField)))
                    .addGroup(jRegisterPanelLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jRegisterButton)))
                .addContainerGap(594, Short.MAX_VALUE))
        );
        jRegisterPanelLayout.setVerticalGroup(
            jRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRegisterPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRegisterNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRegisterSurnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jRegisterEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jRegisterPWTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jRegisterPW2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRegisterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(35, 35, 35)
                .addComponent(jRegisterButton)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jMainTabbedPane.addTab("Register", jRegisterPanel);

        jLabel10.setText("Product ID :");

        jLabel11.setText("Product Name:");

        jLabel12.setText("Weight :");

        jLabel13.setText("Price :");

        jLabel14.setText("Expiry Date :");

        jLabel15.setText("Estimated date to Order :");

        jSaveProductButton.setText("Save Product");
        jSaveProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveProductButtonActionPerformed(evt);
            }
        });

        jUploadImageButton.setText("Upload Image");
        jUploadImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUploadImageButtonActionPerformed(evt);
            }
        });

        jLabel16.setText("Product Image :");

        jUploadImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marketingsoftware/download.jpg"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel17.setText("Add New Product");

        jLabel18.setText("Number of Product :");

        javax.swing.GroupLayout jProductPanelLayout = new javax.swing.GroupLayout(jProductPanel);
        jProductPanel.setLayout(jProductPanelLayout);
        jProductPanelLayout.setHorizontalGroup(
            jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jProductPanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jProductPanelLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(40, 40, 40)
                        .addComponent(jPNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addGap(40, 40, 40)
                        .addComponent(jUploadImageButton))
                    .addGroup(jProductPanelLayout.createSequentialGroup()
                        .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jProductPanelLayout.createSequentialGroup()
                                .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(105, 105, 105)
                                .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPPriceTextField)
                                    .addComponent(jPWeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jProductPanelLayout.createSequentialGroup()
                                .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPExpiryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPOrderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jProductPanelLayout.createSequentialGroup()
                                .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(69, 69, 69)
                                .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                        .addComponent(jUploadImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(88, 88, 88))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jProductPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jProductPanelLayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(330, 330, 330))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jProductPanelLayout.createSequentialGroup()
                        .addComponent(jSaveProductButton)
                        .addGap(368, 368, 368))))
        );
        jProductPanelLayout.setVerticalGroup(
            jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jProductPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(15, 15, 15)
                .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jProductPanelLayout.createSequentialGroup()
                        .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jPIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jPNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jPWeightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jPPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jPExpiryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jPOrderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jUploadImageLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jPNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jUploadImageButton))
                .addGap(50, 50, 50)
                .addComponent(jSaveProductButton)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jMainTabbedPane.addTab("Add Product", jProductPanel);

        jDisplayProductComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel19.setText("Select Product from drop down");

        jDiaplayProductTextArea.setColumns(20);
        jDiaplayProductTextArea.setRows(5);
        jScrollPane1.setViewportView(jDiaplayProductTextArea);

        jDisplayProductButton.setText("Show");
        jDisplayProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDisplayProductButtonActionPerformed(evt);
            }
        });

        AddtoBasket.setText("Add to Basket");
        AddtoBasket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddtoBasketActionPerformed(evt);
            }
        });

        jDisplayProduct_WishListButton.setText("Add ro WishList");
        jDisplayProduct_WishListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDisplayProduct_WishListButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDisplayProductPanelLayout = new javax.swing.GroupLayout(jDisplayProductPanel);
        jDisplayProductPanel.setLayout(jDisplayProductPanelLayout);
        jDisplayProductPanelLayout.setHorizontalGroup(
            jDisplayProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDisplayProductPanelLayout.createSequentialGroup()
                .addGroup(jDisplayProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDisplayProductPanelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDisplayProductPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(jDisplayProductComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDisplayProductPanelLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jDisplayProductButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jDisplayProductLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
            .addGroup(jDisplayProductPanelLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jDisplayProduct_WishListButton)
                .addGap(79, 79, 79)
                .addComponent(AddtoBasket)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDisplayProductPanelLayout.setVerticalGroup(
            jDisplayProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDisplayProductPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jDisplayProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDisplayProductLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDisplayProductPanelLayout.createSequentialGroup()
                        .addGroup(jDisplayProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jDisplayProductComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDisplayProductButton)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jDisplayProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddtoBasket)
                    .addComponent(jDisplayProduct_WishListButton))
                .addContainerGap())
        );

        jMainTabbedPane.addTab("Display Product", jDisplayProductPanel);

        jBasketTextArea.setColumns(20);
        jBasketTextArea.setRows(5);
        jScrollPane4.setViewportView(jBasketTextArea);

        jremovefrombasketButton.setText("Remove");
        jremovefrombasketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jremovefrombasketButtonActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel33.setText("Enter Product Name to Remove from Basket");

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setText("Display Total Price");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jshowPriceButton.setText("Total Price :");
        jshowPriceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jshowPriceButtonActionPerformed(evt);
            }
        });

        jDisplayBAsketButton.setText("Display Basket");
        jDisplayBAsketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDisplayBAsketButtonActionPerformed(evt);
            }
        });

        jLabel36.setText("Enter Account Number :");

        jLabel37.setText("             Name :");

        jPlaceOrderBasketButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPlaceOrderBasketButton.setText("Place Order");
        jPlaceOrderBasketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPlaceOrderBasketButtonActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel38.setText("     BASKET");

        jaddWishListButton.setText("Add Wish List to Basket");
        jaddWishListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddWishListButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jBasketPanelLayout = new javax.swing.GroupLayout(jBasketPanel);
        jBasketPanel.setLayout(jBasketPanelLayout);
        jBasketPanelLayout.setHorizontalGroup(
            jBasketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBasketPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jBasketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jBasketPanelLayout.createSequentialGroup()
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(457, 457, 457))
                    .addGroup(jBasketPanelLayout.createSequentialGroup()
                        .addComponent(jaddWishListButton)
                        .addGroup(jBasketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jBasketPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jBasketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBasketPanelLayout.createSequentialGroup()
                                        .addGroup(jBasketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBasketPanelLayout.createSequentialGroup()
                                                .addComponent(jTextField1)
                                                .addGap(18, 18, 18)
                                                .addComponent(jremovefrombasketButton)
                                                .addGap(3, 3, 3)))
                                        .addGap(160, 160, 160))
                                    .addGroup(jBasketPanelLayout.createSequentialGroup()
                                        .addGroup(jBasketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jBasketPanelLayout.createSequentialGroup()
                                                .addComponent(jshowPriceButton)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jBasketPanelLayout.createSequentialGroup()
                                                .addGroup(jBasketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel36)
                                                    .addComponent(jLabel37))
                                                .addGap(18, 18, 18)
                                                .addGroup(jBasketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jTextField2)
                                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jBasketPanelLayout.createSequentialGroup()
                                                .addGap(93, 93, 93)
                                                .addComponent(jPlaceOrderBasketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(78, 78, 78))))
                            .addGroup(jBasketPanelLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabel34)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jBasketPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jDisplayBAsketButton)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jBasketPanelLayout.setVerticalGroup(
            jBasketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBasketPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jBasketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jBasketPanelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jDisplayBAsketButton)
                        .addGap(26, 26, 26)
                        .addComponent(jaddWishListButton)
                        .addContainerGap(228, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBasketPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jBasketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4)
                            .addGroup(jBasketPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel33)
                                .addGap(18, 18, 18)
                                .addGroup(jBasketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jremovefrombasketButton))
                                .addGap(47, 47, 47)
                                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jBasketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jshowPriceButton, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                                    .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(51, 51, 51)
                                .addGroup(jBasketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel36))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jBasketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel37)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jPlaceOrderBasketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51))))
        );

        jMainTabbedPane.addTab("Basket", jBasketPanel);

        jLabel20.setText("Select Product :");

        jLabel21.setText("Number of Product :");

        jLabel22.setText("Expected date of Delivery :");

        jLabel24.setText("Select Supplier :");

        jNumberOfProductSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jNumberOfProductSpinner.setValue(40);

        jPlaceOrderButton.setText("Place Order");
        jPlaceOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPlaceOrderButtonActionPerformed(evt);
            }
        });

        jShowSupplierButton.setText("Show Supplier Details");
        jShowSupplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowSupplierButtonActionPerformed(evt);
            }
        });

        jSupplierDetailTextArea.setColumns(20);
        jSupplierDetailTextArea.setRows(5);
        jScrollPane2.setViewportView(jSupplierDetailTextArea);

        jAmountButton.setText("Amount to be Paid :");
        jAmountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAmountButtonActionPerformed(evt);
            }
        });

        jLabel23.setText("£");

        javax.swing.GroupLayout jReorderPanelLayout = new javax.swing.GroupLayout(jReorderPanel);
        jReorderPanel.setLayout(jReorderPanelLayout);
        jReorderPanelLayout.setHorizontalGroup(
            jReorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jReorderPanelLayout.createSequentialGroup()
                .addGroup(jReorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jReorderPanelLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jPlaceOrderButton))
                    .addGroup(jReorderPanelLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jReorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20))
                        .addGap(47, 47, 47)
                        .addGroup(jReorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNumberOfProductSpinner)
                            .addComponent(jSelectProductComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(457, 457, 457))
            .addGroup(jReorderPanelLayout.createSequentialGroup()
                .addGroup(jReorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jReorderPanelLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jReorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24)
                            .addComponent(jAmountButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jReorderPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jShowSupplierButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jReorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jReorderPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jReorderPanelLayout.createSequentialGroup()
                        .addGroup(jReorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSelectSupplierComboBox, 0, 219, Short.MAX_VALUE)
                            .addComponent(jExpectedDeliveryDateTextField)
                            .addGroup(jReorderPanelLayout.createSequentialGroup()
                                .addComponent(jAmountPaidLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(457, 457, 457))))
        );
        jReorderPanelLayout.setVerticalGroup(
            jReorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jReorderPanelLayout.createSequentialGroup()
                .addGroup(jReorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jReorderPanelLayout.createSequentialGroup()
                        .addComponent(jNumberOfProductSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jExpectedDeliveryDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jReorderPanelLayout.createSequentialGroup()
                        .addGroup(jReorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSelectProductComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22)))
                .addGroup(jReorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jReorderPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jAmountButton))
                    .addGroup(jReorderPanelLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jReorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jAmountPaidLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jReorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSelectSupplierComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jReorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jReorderPanelLayout.createSequentialGroup()
                        .addComponent(jShowSupplierButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPlaceOrderButton)
                .addGap(30, 30, 30))
        );

        jMainTabbedPane.addTab("Reorder", jReorderPanel);

        jLabel25.setText("Name :");

        jLabel26.setText("Building Number :");

        jLabel27.setText("Street :");

        jLabel28.setText("Area :");

        jLabel29.setText("Post Code :");

        jLabel30.setText("Town :");

        jLabel31.setText("Country :");

        jSaveSupplierButton.setText("Save Supplier");
        jSaveSupplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveSupplierButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jAddSupplierPanelLayout = new javax.swing.GroupLayout(jAddSupplierPanel);
        jAddSupplierPanel.setLayout(jAddSupplierPanelLayout);
        jAddSupplierPanelLayout.setHorizontalGroup(
            jAddSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAddSupplierPanelLayout.createSequentialGroup()
                .addGroup(jAddSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jAddSupplierPanelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jAddSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jAddSupplierPanelLayout.createSequentialGroup()
                                .addGroup(jAddSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel31))
                                .addGap(18, 18, 18)
                                .addGroup(jAddSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCountryTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                    .addComponent(jTownTextField)
                                    .addComponent(jPostCodeTextField)
                                    .addComponent(jAreaTextField)
                                    .addComponent(jStreetTextField)
                                    .addComponent(jBuildingNoTextField)))
                            .addGroup(jAddSupplierPanelLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jAddSupplierPanelLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jSaveSupplierButton)))
                .addGap(551, 551, 551))
        );
        jAddSupplierPanelLayout.setVerticalGroup(
            jAddSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAddSupplierPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jAddSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jAddSupplierPanelLayout.createSequentialGroup()
                        .addGroup(jAddSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jAddSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(jBuildingNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jAddSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jStreetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jAddSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jAreaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel29))
                    .addComponent(jPostCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jAddSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jTownTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jAddSupplierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jCountryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jSaveSupplierButton)
                .addGap(101, 101, 101))
        );

        jMainTabbedPane.addTab("Add Supplier", jAddSupplierPanel);

        jDisplayOrdersTextArea.setColumns(20);
        jDisplayOrdersTextArea.setRows(5);
        jScrollPane3.setViewportView(jDisplayOrdersTextArea);

        jDisplayPendingOrdersButton.setText("Display Pending Orders");
        jDisplayPendingOrdersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDisplayPendingOrdersButtonActionPerformed(evt);
            }
        });

        jSupplyProductButton.setText("Supply all Products");
        jSupplyProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSupplyProductButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jShowOrdersPanelLayout = new javax.swing.GroupLayout(jShowOrdersPanel);
        jShowOrdersPanel.setLayout(jShowOrdersPanelLayout);
        jShowOrdersPanelLayout.setHorizontalGroup(
            jShowOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jShowOrdersPanelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jShowOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jShowOrdersPanelLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jSupplyProductButton))
                    .addGroup(jShowOrdersPanelLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jDisplayPendingOrdersButton)))
                .addContainerGap(279, Short.MAX_VALUE))
        );
        jShowOrdersPanelLayout.setVerticalGroup(
            jShowOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jShowOrdersPanelLayout.createSequentialGroup()
                .addGroup(jShowOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jShowOrdersPanelLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jDisplayPendingOrdersButton)
                        .addGap(63, 63, 63)
                        .addComponent(jSupplyProductButton))
                    .addGroup(jShowOrdersPanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jMainTabbedPane.addTab("Show Orders", jShowOrdersPanel);

        javax.swing.GroupLayout jMainPanelLayout = new javax.swing.GroupLayout(jMainPanel);
        jMainPanel.setLayout(jMainPanelLayout);
        jMainPanelLayout.setHorizontalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jMainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jMainPanelLayout.setVerticalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMainTabbedPane)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar.add(jMenu2);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jStatusPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jStatusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSupplyProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSupplyProductButtonActionPerformed
        // TODO add your handling code here:
        orderlist.ClearOrderList();
        orderlist.SaveToFile(false);
        jDisplayOrdersTextArea.setText("");
    }//GEN-LAST:event_jSupplyProductButtonActionPerformed

    private void jDisplayPendingOrdersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDisplayPendingOrdersButtonActionPerformed
        // TODO add your handling code here:
        orderlist.Display(jDisplayOrdersTextArea);
    }//GEN-LAST:event_jDisplayPendingOrdersButtonActionPerformed

    private void jSaveSupplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveSupplierButtonActionPerformed
        // TODO add your handling code here:
        supplier = new Supplier(jNameTextField.getText(),(new Address(Integer.valueOf(jBuildingNoTextField.getText()),
            jStreetTextField.getText(),jAreaTextField.getText(),jPostCodeTextField.getText(),jTownTextField.getText(),
            jCountryTextField.getText())));
jSelectSupplierComboBox.addItem(jNameTextField.getText());
supplier.SaveToFile(true);
supplierList.Add(supplier);
    }//GEN-LAST:event_jSaveSupplierButtonActionPerformed

    private void jAmountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAmountButtonActionPerformed
        // TODO add your handling code here:
        product = new Product();
        product = list.getProduct(String.valueOf(jSelectProductComboBox.getSelectedItem()));
        int quantity = (int) jNumberOfProductSpinner.getValue();
        double price = product.getPrice();
        jAmountPaidLabel.setText(String.valueOf(price*quantity));
    }//GEN-LAST:event_jAmountButtonActionPerformed

    private void jShowSupplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowSupplierButtonActionPerformed
        // TODO add your handling code here:
        supplier = new Supplier();
        supplier = supplierList.getSupplier(String.valueOf(jSelectSupplierComboBox.getSelectedItem()));
        jSupplierDetailTextArea.setText("");
        supplier.Display(jSupplierDetailTextArea);
    }//GEN-LAST:event_jShowSupplierButtonActionPerformed

    private void jPlaceOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPlaceOrderButtonActionPerformed
        // TODO add your handling code here:
        ProductList p = new ProductList();
        SupplierList s = new SupplierList();
        Order order = new Order(p.getProduct(String.valueOf(jSelectProductComboBox.getSelectedItem())),
            (int)(jNumberOfProductSpinner.getValue()),jExpectedDeliveryDateTextField.getText(),
            s.getSupplier(String.valueOf(jSelectSupplierComboBox.getSelectedItem())));
        order.SaveToFile(true);
    }//GEN-LAST:event_jPlaceOrderButtonActionPerformed

    private void jshowPriceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jshowPriceButtonActionPerformed
        // TODO add your handling code here:
        price =0;
        for (int i = 0; i < basket.size(); i++) {
            price = price + list.getProduct(basket.get(i)).getPrice();
        }
        jLabel35.setText(String.valueOf(price)+" £");
    }//GEN-LAST:event_jshowPriceButtonActionPerformed

    private void jDisplayProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDisplayProductButtonActionPerformed
        // TODO add your handling code here:
        product = new Product();
        product = list.getProduct(String.valueOf(jDisplayProductComboBox.getSelectedItem()));
        jDiaplayProductTextArea.setText("");
        product.Display(jDiaplayProductTextArea);
        product.ShowImage(jDisplayProductLabel);
    }//GEN-LAST:event_jDisplayProductButtonActionPerformed

    private void jUploadImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUploadImageButtonActionPerformed
        // TODO add your handling code here:   }
        product.UploadImage(jUploadImageLabel);
    }//GEN-LAST:event_jUploadImageButtonActionPerformed

    private void jSaveProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveProductButtonActionPerformed
        // TODO add your handling code here:
        product.Edit(Integer.valueOf(jPIDTextField.getText()),
            jPNameTextField.getText(), Double.valueOf(jPWeightTextField.getText()),
            Double.valueOf(jPPriceTextField.getText()), jPExpiryTextField.getText(),
            jPOrderTextField.getText(),Integer.valueOf(jPNumberTextField.getText()));
        try {
            product.SaveImage();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Please try Again");
        }
        product.SaveToFile(true);
        JOptionPane.showMessageDialog(this, "Product Saved Succesfully");
        list = new ProductList();
        jDisplayProductComboBox.addItem(jPNameTextField.getText());
        jSelectProductComboBox.addItem(jPNameTextField.getText());
    }//GEN-LAST:event_jSaveProductButtonActionPerformed

    private void jRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegisterButtonActionPerformed
        // TODO add your handling code here:
        User user= new User(jRegisterNameTextField.getText(),jRegisterSurnameTextField.getText(),
            jRegisterEmailTextField.getText(),jRegisterPWTextField.getText(),jRegisterPW2TextField.getText(),
            String.valueOf(jRegisterComboBox.getSelectedItem()));
        if(user.SaveUser()){
            JOptionPane.showMessageDialog(this,"Welcome! you are Officially Register now..");
            jMainTabbedPane.add("Login", jLoginTab);
            jMainTabbedPane.remove(0);
        }
        else{
            JOptionPane.showMessageDialog(this,"Please try to Register Again");
        }
    }//GEN-LAST:event_jRegisterButtonActionPerformed

    private void jRegisterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegisterComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRegisterComboBoxActionPerformed

    private void jLoginRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginRegisterButtonActionPerformed
        // TODO add your handling code here:
        jMainTabbedPane.addTab("Register", jRegisterTabInMemory);
        jMainTabbedPane.setSelectedIndex(1);
        jMainTabbedPane.remove(0);
    }//GEN-LAST:event_jLoginRegisterButtonActionPerformed

    private void jLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButtonActionPerformed
        // TODO add your handling code here        
        User user = new User();
        if(user.isUser(jLoginEmailTextField.getText(), String.valueOf(jLoginPasswordField.getPassword()),
            String.valueOf(jLoginComboBox.getSelectedItem()))){
            if(String.valueOf(jLoginComboBox.getSelectedItem()) == "Owner"){
                jMainTabbedPane.addTab("Add Product", addproduct);
                jMainTabbedPane.addTab("Display Product", displayproduct);
                jMainTabbedPane.addTab("Basket", basketTab);
                jMainTabbedPane.addTab("Re-Order",reorder);
                jMainTabbedPane.addTab("Add Supplier", addsupplier);
                jMainTabbedPane.setSelectedIndex(1);
            }
            else if(String.valueOf(jLoginComboBox.getSelectedItem()) == "Customer"){
                jMainTabbedPane.addTab("Display Product", displayproduct);
                jMainTabbedPane.addTab("Basket", basketTab);
                jMainTabbedPane.setSelectedIndex(1);
            }
            else if(String.valueOf(jLoginComboBox.getSelectedItem()) == "Supplier"){
                jMainTabbedPane.addTab("Show Orders", showorders);
                jMainTabbedPane.setSelectedIndex(1);
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"No User Found");
        }

        ArrayList<String> name = new ArrayList<String>();
        name = nameList.name();
        jDisplayProductComboBox.removeAllItems();
        jDisplayProductComboBox.addItem("Select Item");

        jSelectProductComboBox.removeAllItems();
        jSelectProductComboBox.addItem("Select Item");

        for(int i=0;i<name.size();i++){
            jDisplayProductComboBox.addItem(name.get(i));
            jSelectProductComboBox.addItem(name.get(i));
        }

        ArrayList<String> suppliername = new ArrayList<String>();
        suppliername = suppliernameList.name();
        jSelectSupplierComboBox.removeAllItems();
        jSelectSupplierComboBox.addItem("Select Supplier");
        for(int i=0;i<suppliername.size();i++){
            jSelectSupplierComboBox.addItem(suppliername.get(i));
        }
        
        wishList = new ProductList();
        
    }//GEN-LAST:event_jLoginButtonActionPerformed

    private void AddtoBasketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddtoBasketActionPerformed
        // TODO add your handling code here:
        String pName = String.valueOf(jDisplayProductComboBox.getSelectedItem());
        basket.add(pName);
        JOptionPane.showMessageDialog(this, "Product Added to Basket");
    }//GEN-LAST:event_AddtoBasketActionPerformed

    private void jDisplayProduct_WishListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDisplayProduct_WishListButtonActionPerformed
        // TODO add your handling code here:
        Product p = list.getProduct(String.valueOf(jDisplayProductComboBox.getSelectedItem()));
        wishList.add(p);
        wishList.SaveToFileWishList(false);
        JOptionPane.showMessageDialog(this, "Product Added to Wish List");
    }//GEN-LAST:event_jDisplayProduct_WishListButtonActionPerformed

    private void jaddWishListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddWishListButtonActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < wishList.Size(); i++) {
            basket.add(wishList.Get(i).getProductName());
        }
        JOptionPane.showMessageDialog(this, "WishList added to Basket");
        this.jDisplayBAsketButtonActionPerformed(evt);
    }//GEN-LAST:event_jaddWishListButtonActionPerformed

    private void jDisplayBAsketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDisplayBAsketButtonActionPerformed
        // TODO add your handling code here:
        jBasketTextArea.setText("");
        for (int i = 0; i < basket.size(); i++) {
            list.getProduct(basket.get(i)).DisplayNamePrice(jBasketTextArea);
        }
    }//GEN-LAST:event_jDisplayBAsketButtonActionPerformed

    private void jremovefrombasketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jremovefrombasketButtonActionPerformed
        // TODO add your handling code here:
        basket.remove(jTextField1.getText());
        JOptionPane.showMessageDialog(this, "Item Removed from Basket");
        this.jDisplayBAsketButtonActionPerformed(evt);
    }//GEN-LAST:event_jremovefrombasketButtonActionPerformed

    private void jPlaceOrderBasketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPlaceOrderBasketButtonActionPerformed
        // TODO add your handling code here:
        int accNo = Integer.valueOf(jTextField2.getText());
        String name = jTextField4.getText();
        if(account.getAccount(accNo).transfer(account.getAccount(12345), price)){
            account.SaveToFile(false);
            JOptionPane.showMessageDialog(this, "Order Placed Succesfully");
        }
        else{
            JOptionPane.showMessageDialog(this, "Please Check Account Details");
        }
        
    }//GEN-LAST:event_jPlaceOrderBasketButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */ 
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    double price;
    Product product  = new Product();
    ProductList list = new ProductList();
    ProductList nameList = new ProductList();
    Supplier supplier = new Supplier();
    SupplierList suppliernameList = new SupplierList();
    SupplierList supplierList = new SupplierList();
    OrderList orderlist = new OrderList();
    BankAccountList account = new BankAccountList();
    ProductList wishList;
    ArrayList<String> basket = new ArrayList<String>();
    
    private java.awt.Component jRegisterTabInMemory;
    private java.awt.Component jLoginTab;
    private java.awt.Component addproduct;
    private java.awt.Component displayproduct;
    private java.awt.Component reorder;
    private java.awt.Component addsupplier;
    private java.awt.Component showorders;
    private java.awt.Component basketTab;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddtoBasket;
    private javax.swing.JPanel jAddSupplierPanel;
    private javax.swing.JButton jAmountButton;
    private javax.swing.JLabel jAmountPaidLabel;
    private javax.swing.JTextField jAreaTextField;
    private javax.swing.JPanel jBasketPanel;
    private javax.swing.JTextArea jBasketTextArea;
    private javax.swing.JTextField jBuildingNoTextField;
    private javax.swing.JTextField jCountryTextField;
    private javax.swing.JTextArea jDiaplayProductTextArea;
    private javax.swing.JButton jDisplayBAsketButton;
    private javax.swing.JTextArea jDisplayOrdersTextArea;
    private javax.swing.JButton jDisplayPendingOrdersButton;
    private javax.swing.JButton jDisplayProductButton;
    private javax.swing.JComboBox<String> jDisplayProductComboBox;
    private javax.swing.JLabel jDisplayProductLabel;
    private javax.swing.JPanel jDisplayProductPanel;
    private javax.swing.JButton jDisplayProduct_WishListButton;
    private javax.swing.JTextField jExpectedDeliveryDateTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jLoginButton;
    public static javax.swing.JComboBox<String> jLoginComboBox;
    private javax.swing.JTextField jLoginEmailTextField;
    private javax.swing.JPanel jLoginPanel;
    private javax.swing.JPasswordField jLoginPasswordField;
    private javax.swing.JButton jLoginRegisterButton;
    private javax.swing.JPanel jMainPanel;
    private javax.swing.JTabbedPane jMainTabbedPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JTextField jNameTextField;
    private javax.swing.JSpinner jNumberOfProductSpinner;
    private javax.swing.JTextField jPExpiryTextField;
    private javax.swing.JTextField jPIDTextField;
    private javax.swing.JTextField jPNameTextField;
    private javax.swing.JTextField jPNumberTextField;
    private javax.swing.JTextField jPOrderTextField;
    private javax.swing.JTextField jPPriceTextField;
    private javax.swing.JTextField jPWeightTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jPlaceOrderBasketButton;
    private javax.swing.JButton jPlaceOrderButton;
    private javax.swing.JTextField jPostCodeTextField;
    private javax.swing.JPanel jProductPanel;
    private javax.swing.JButton jRegisterButton;
    private javax.swing.JComboBox<String> jRegisterComboBox;
    private javax.swing.JTextField jRegisterEmailTextField;
    private javax.swing.JTextField jRegisterNameTextField;
    private javax.swing.JTextField jRegisterPW2TextField;
    private javax.swing.JTextField jRegisterPWTextField;
    private javax.swing.JPanel jRegisterPanel;
    private javax.swing.JTextField jRegisterSurnameTextField;
    private javax.swing.JPanel jReorderPanel;
    private javax.swing.JButton jSaveProductButton;
    private javax.swing.JButton jSaveSupplierButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JComboBox<String> jSelectProductComboBox;
    private javax.swing.JComboBox<String> jSelectSupplierComboBox;
    private javax.swing.JPanel jShowOrdersPanel;
    private javax.swing.JButton jShowSupplierButton;
    private javax.swing.JPanel jStatusPanel;
    private javax.swing.JTextField jStreetTextField;
    private javax.swing.JTextArea jSupplierDetailTextArea;
    private javax.swing.JButton jSupplyProductButton;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTownTextField;
    private javax.swing.JButton jUploadImageButton;
    public javax.swing.JLabel jUploadImageLabel;
    private javax.swing.JButton jaddWishListButton;
    private javax.swing.JButton jremovefrombasketButton;
    private javax.swing.JButton jshowPriceButton;
    // End of variables declaration//GEN-END:variables
}